-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 09:42:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema etownprking
-- -----------------------------------------------------
DROP DATABASE `etownparking`;
CREATE DATABASE `etownparking`;
USE `etownparking` ;

-- -----------------------------------------------------
-- Table `etownprking`.`badgeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etownparking`.`badgeType` ;

CREATE TABLE IF NOT EXISTS `etownparking`.`badgeType` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`typeID`));


-- -----------------------------------------------------
-- Table `etownprking`.`parkingLots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etownparking`.`parkingLots` ;

CREATE TABLE IF NOT EXISTS `etownparking`.`parkingLots` (
  `lotID` INT NOT NULL AUTO_INCREMENT,
  `lotName` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`lotID`));


-- -----------------------------------------------------
-- Table `etownprking`.`parkingRules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etownparking`.`parkingRules` ;

CREATE TABLE IF NOT EXISTS `etownparking`.`parkingRules` (
  `ruleID` INT NOT NULL AUTO_INCREMENT,
  `typeID` INT NOT NULL,
  `lotID` INT NOT NULL,
  `day` VARCHAR(45) NULL,
  `startTime` TIME NULL,
  `endTime` TIME NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`ruleID`),
  CONSTRAINT `typeID`
    FOREIGN KEY (`typeID`)
    REFERENCES `etownparking`.`badgeType` (`typeID`),
  CONSTRAINT `lotID`
    FOREIGN KEY (`lotID`)
    REFERENCES `etownparking`.`parkingLots` (`lotID`)
);
